### DISCUSSION TITLE
Docker Compose Help

### DISCUSSION THREAD

**Discussion by juftin** [juftin/camply#330] [Q&A] [answered]
Question from an email:

> I have it working in cli and can get docker running from command line too, but an struggling to get it to work with docker compose.  Could you possibly share an example that doesn't use a search-example yaml with everything in the compose itself including push user and token?  I'm relatively new to docker compose so that would easily be the issue but something is tripping up the compose.

**Comment by juftin** [comment, marked as answer]
## camply + docker 

Camply has some existing docker documentation here: https://juftin.com/camply/how_to_run/#running-in-docker

Here's an example:

```shell
docker run --rm -d \
  --name camply-detached-example \
  --env PUSHOVER_PUSH_TOKEN=${PUSHOVER_PUSH_TOKEN} \
  --env PUSHOVER_PUSH_USER=${PUSHOVER_PUSH_USER} \
  --env TZ="America/Denver" \
  juftin/camply \
  camply campsites \
      --rec-area 2991 \
      --start-date 2023-08-01 \
      --end-date 2023-09-01 \
      --search-forever \
      --notifications pushover
```

There is also an existing docker-compose example here (although it uses a YAML file as noted): https://github.com/juftin/camply/blob/main/docs/examples/docker-compose.yaml

```yaml
version: "3.7"
services:
    camply:
        container_name: camply-docker-compose-example
        image: juftin/camply:latest
        environment:
            TZ: America/Denver
        volumes:
            - ${PWD}/example.camply:/home/camply/.camply
            - ${PWD}/example_search.yaml:/home/camply/search.yaml
        command: camply campsites --yaml-config /home/camply/search.yaml
        restart: unless-stopped
```

Putting all that together we can come to a docker-compose file that looks something like this:

```yaml
services:
    camply:
        container_name: camply-docker-compose-example
        image: juftin/camply:latest
        platform: linux/amd64
        environment:
            TZ: America/Denver
            PUSHOVER_PUSH_USER: xxxxxx
        restart: unless-stopped
        command: |
          camply campsites
              --rec-area 2991
              --start-date 2024-08-01
              --end-date 2024-09-01
              --search-forever
              --notifications pushover
```
 
The slashes are confusing - you'd want to use them if you were running multi-line commands on a Unix (mac / linux) shell. But YAML files don't like them. If that's too confusing you could also use the "array syntax" for docker compose:

```yaml
services:
  camply:
    container_name: camply-docker-compose-example
    image: juftin/camply:latest
    platform: linux/amd64
    environment:
      TZ: America/Denver
      PUSHOVER_PUSH_USER: xxxxxx
    restart: unless-stopped
    command:
      - camply
      - campsites
      - --rec-area
      - "2991"
      - --start-date
      - "2024-08-01"
      - --end-date
      - "2024-09-01"
      - --search-forever
      - --notifications
      - pushover
```

Let me know if you run into any further issues, hope this gets you squared away.
