### DISCUSSION TITLE
Search for specific sites at specfiic dates

### DISCUSSION THREAD

**Discussion by thornto4** [juftin/camply#334] [Ideas]
Thank you for this wonderful tool! 

Is it possible to search for specific sites at specific dates?

For example, we're heading out on a summer trip spanning multiple parks with our parents. We know the date ranges we'll be at each park. And we know what campsites we'd like to receive notifications on if they become available so we can stay close together.

This can be pretty common if you've managed to snag _some but not all_ of your desired dates at a particular site and you'd like to catch openings to extend your stay and avoid unnecessary site hopping.

It looks like the camply CLI supports searching for multiple dates. And also searching for multiple sites.  But it doesn't give us a way to say which dates belong to which sites (as far as I can tell).

Short of running two independent sessions, is there a way to achieve this level of granularity?

In yaml terms, it might be something like a sequence of mappings:

```yaml
campsites:
    - 
    campsite: 10099495 #  Signal Mountain Campground, Grand Teton National Park, WY
    start_date: 2024-06-12
    end_date: 2024-06-17
    - 
    campsite: 232463 # Rocky Mountain National Park Moraine Campground, Rocky Mountain National Park, CO
    start_date: 2024-06-18
    end_date: 2024-06-23
```
_Assuming I've got the formatting right_
       
It's perhaps similar in spirit to #297 , although that casts a much wider net, and this would extend the concept down to a more granular search.

_For more context, I just had my first availability notification using the camply, so woo! And it seems to have notified me before recreation.gov (curiously). So kudos! As I'm learning to use the tool, I did notice the hit was a false positive for my usage, which prompted this question_
