### ISSUE TITLE
Continuous Search not working with YAML file

### ISSUE THREAD

**Issue by boydthomson** [juftin/camply#352]
**Describe the bug**

I have tried every conceivable combination of continuous: true and search-forever, yet no matter what, camply exits as soon as it finds a site.

**Original Camply Command (with `--debug`)**

YAML:
```
provider: goingtocamp
recreation_area: # (LIST OR SINGLE ENTRY)
  - 12
campgrounds: # ENTIRE FIELD CAN BE OMITTED IF NOT USED - (LIST OR SINGLE ENTRY)
  - -2147483647 # Alice Lake
  - -2147483606 # Golden Ears
  - -2147483550 # Porteau Cove
  - -2147483618 # Manning Park
  - -2147483535 # Silver Lake

start_date:
  - 2024-06-26
  - 2024-06-27
  - 2024-06-27
  - 2024-07-03
  - 2024-07-10
  - 2024-07-17
  - 2024-07-24
  - 2024-07-31
  - 2024-06-27
  - 2024-07-04
  - 2024-07-11
  - 2024-07-18
  - 2024-07-25
  - 2024-08-01
end_date:
  - 2024-06-29
  - 2024-06-29
  - 2024-06-30
  - 2024-07-06
  - 2024-07-13
  - 2024-07-20
  - 2024-07-27
  - 2024-08-03
  - 2024-06-30
  - 2024-07-07
  - 2024-07-14
  - 2024-07-21
  - 2024-07-28
  - 2024-08-04

notifications:
  - pushover
  - email

continuous: true
```

continuous: true

**Comment by juftin** [comment]
Can you supply your YAML file as written using [GitHub code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)?

**Comment by juftin** [comment]
Actually, I was able to decipher the YAML format @boydthomson 
<details><summary>Details</summary>
<p>

```yaml
provider: goingtocamp
recreation_area: 12
campgrounds:
  - -2147483647 # Alice Lake
  - -2147483606 # Golden Ears
  - -2147483550 # Porteau Cove
  - -2147483618 # Manning Park
  - -2147483535 # Silver Lake
start_date:
  - 2024-06-28
  - 2024-07-03
  - 2024-07-10
  - 2024-07-17
  - 2024-07-24
  - 2024-07-31
  - 2024-06-27
  - 2024-07-04
  - 2024-07-11
  - 2024-07-18
  - 2024-07-25
  - 2024-08-01
end_date:
  - 2024-06-30
  - 2024-07-06
  - 2024-07-13
  - 2024-07-20
  - 2024-07-27
  - 2024-08-03
  - 2024-06-30
  - 2024-07-07
  - 2024-07-14
  - 2024-07-21
  - 2024-07-28
  - 2024-08-04
notifications:
  - pushover
  - email
continuous: true
```

</p>
</details> 

You're missing the `search_forever` field in the YAML file (I think you might be trying `search-forever`)

https://juftin.com/camply/command_line_usage/#using-a-yaml-configuration-file-to-search-for-campsites
